### ISSUE TITLE
dht has a startup race condition with listen

### ISSUE THREAD

**Issue by max-mapper** [maxogden/discovery-channel#1]
if you call `discovery.announce` multiple times before the DHT has fully initialized then it results in `dht.listen` being called multiple times which causes:

``` js
Error: dht is already listening
    at DHT.listen (/Users/max/src/js/discovery-channel/node_modules/bittorrent-dht/client.js:185:46)
```

the bittorrent-dht module should be using deferred open (with e.g. thunky) but isnt

**Comment by ralphtheninja** [comment]
+1

**Comment by okdistribute** [comment]
@mafintosh @feross is this fixed now?

**Comment by mafintosh** [comment]
Ah yes
