### ISSUE TITLE
dht.lookup stops after a while

### ISSUE THREAD

**Issue by mafintosh** [maxogden/discovery-channel#2]
Just noticed my two remote peers stopped connecting to each other because they stopped looking for new peers in the dht. I think we need to call `dht.lookup` on regular intervals. Maybe expose that as `lookup.update()` in this module?

**Comment by max-mapper** [comment]
cant you just call `dht.lookup` again?

**Comment by max-mapper** [comment]
when I was writing this I expected `.lookup` to go out and look up the hash, and then the lookup finishes. if the user wanted to do another lookup they would have to call `.lookup` again. But I guess for most long-lived use cases you want to do lookup on an interval to make sure you find new peers in the swarm?

**Comment by mafintosh** [comment]
yea exactly. since it returns an event-emitter it would be nice to be able to call `.update()` on that event emitter to have it republish the lookup message

**Comment by mafintosh** [comment]
Fixed in latest release
